[package]
name = "groma-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "groma-api"
path = "src/main.rs"

[dependencies]
bim-convert = { path = "../../crates/bim-convert" }
clap = { workspace = true }
mimalloc = "0.1.52"
serde = { workspace = true }
serde_json = { workspace = true }
tiny_http = { workspace = true }

[lints]
workspace = true
