#!/usr/bin/env python3
"""Generate the checked-in Revit 2023 identifier and Forge spec tables."""

from __future__ import annotations

import argparse
import json
import math
import re
import struct
import zlib
from collections import defaultdict
from html.parser import HTMLParser
from pathlib import Path

PAGE_STORED = 65_249
PAGE_PAYLOAD = 64_896
FOOT_TO_METRE = 0.3048
VERSION = re.compile(r"-\d+\.\d+\.\d+$")


class TableParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.rows: list[list[str]] = []
        self._row: list[str] | None = None
        self._cell: list[str] | None = None

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        del attrs
        if tag == "tr":
            self._row = []
        elif tag in {"td", "th"} and self._row is not None:
            self._cell = []

    def handle_data(self, data: str) -> None:
        if self._cell is not None:
            self._cell.append(data)

    def handle_endtag(self, tag: str) -> None:
        if tag in {"td", "th"} and self._cell is not None and self._row is not None:
            self._row.append(" ".join("".join(self._cell).split()))
            self._cell = None
        elif tag == "tr" and self._row is not None:
            if self._row:
                self.rows.append(self._row)
            self._row = None


def html_rows(path: Path) -> list[list[str]]:
    parser = TableParser()
    parser.feed(path.read_text(encoding="utf-8", errors="replace"))
    return parser.rows


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def enum_members(path: Path, category: bool) -> dict[str, str]:
    valid = re.compile(r"^(?:INVALID|OST_[A-Za-z0-9_]+)$" if category else r"^[A-Z][A-Z0-9_]*$")
    return {
        row[0]: row[1]
        for row in html_rows(path)
        if len(row) >= 2 and valid.fullmatch(row[0])
    }


def enum_values(paths: list[Path], category: bool) -> tuple[dict[str, int], set[str]]:
    valid = re.compile(r"^(?:INVALID|OST_[A-Za-z0-9_]+)$" if category else r"^[A-Z][A-Z0-9_]*$")
    values: dict[str, int] = {}
    newest: set[str] = set()
    for index, path in enumerate(paths):
        for row in html_rows(path):
            if len(row) < 3 or not valid.fullmatch(row[0]):
                continue
            try:
                value = int(row[1].replace(",", ""))
            except ValueError:
                continue
            values.setdefault(row[0], value)
            if index == 0:
                newest.add(row[0])
    return values, newest


def display_name(enum_name: str, description: str) -> str:
    match = re.match(r'^"([^"]+)"', description)
    return match.group(1) if match else enum_name


def generate_parameters(members_path: Path, value_paths: list[Path], output: Path) -> None:
    members = enum_members(members_path, category=False)
    values, newest = enum_values(value_paths, category=False)
    by_code: dict[int, list[str]] = defaultdict(list)
    for name in members:
        if name in values:
            by_code[values[name]].append(name)

    def score(name: str) -> tuple[bool, bool, str]:
        return (name not in newest, "OBSOLETE" in name, name)

    lines = [
        "// @generated by scripts/generate_revit_2023_catalog.py; do not edit.",
        "#![allow(clippy::unreadable_literal)]",
        "use crate::BuiltInParameter;",
        "",
        "pub(super) static VALUES: &[BuiltInParameter] = &[",
    ]
    for code, names in sorted(by_code.items()):
        name = min(names, key=score)
        label = display_name(name, members[name])
        lines.append(
            "    BuiltInParameter { "
            f"code: {code}, enum_name: {rust_string(name)}, display_name: {rust_string(label)} "
            "},"
        )
    lines.extend(["];"])
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    missing = sorted(set(members) - set(values))
    print(f"parameters: {len(by_code)} codes; omitted without a public numeric value: {missing}")


def generate_categories(members_path: Path, value_paths: list[Path], output: Path) -> None:
    members = enum_members(members_path, category=True)
    values, _ = enum_values(value_paths, category=True)
    entries = sorted((values[name], name) for name in members if name in values)
    lines = [
        "// @generated by scripts/generate_revit_2023_catalog.py; do not edit.",
        "#![allow(clippy::unreadable_literal)]",
        "use crate::BuiltInCategory;",
        "",
        "pub(super) static VALUES: &[BuiltInCategory] = &[",
    ]
    for code, name in entries:
        lines.append(
            f"    BuiltInCategory {{ code: {code}, enum_name: {rust_string(name)} }},"
        )
    lines.extend(["];"])
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    missing = sorted(set(members) - set(values))
    if missing:
        raise SystemExit(f"categories missing public numeric values: {missing}")
    print(f"categories: {len(entries)} codes")


def strip_pages(data: bytes) -> bytes:
    full_pages = len(data) // PAGE_STORED
    chunks = [
        data[index * PAGE_STORED : index * PAGE_STORED + PAGE_PAYLOAD]
        for index in range(full_pages)
    ]
    chunks.append(data[full_pages * PAGE_STORED :])
    return b"".join(chunks)


def gzip_body_offset(data: bytes, offset: int) -> int:
    if data[offset : offset + 3] != b"\x1f\x8b\x08":
        raise ValueError("unsupported Global/Latest framing")
    flags = data[offset + 3]
    cursor = offset + 10
    if flags & 4:
        length = int.from_bytes(data[cursor : cursor + 2], "little")
        cursor += 2 + length
    for flag in (8, 16):
        if flags & flag:
            cursor = data.index(0, cursor) + 1
    if flags & 2:
        cursor += 2
    return cursor


def registry_objects(path: Path) -> dict[str, dict[str, object]]:
    data = strip_pages(path.read_bytes())
    gzip_offset = next(offset for offset in (0, 4, 8) if data[offset : offset + 2] == b"\x1f\x8b")
    body = gzip_body_offset(data, gzip_offset)
    decoded = zlib.decompressobj(-15).decompress(data[body:])
    objects: dict[str, dict[str, object]] = {}
    for offset in range(len(decoded) - 8):
        name_units = struct.unpack_from("<I", decoded, offset)[0]
        if not 8 <= name_units <= 200:
            continue
        name_end = offset + 4 + name_units * 2
        try:
            name = decoded[offset + 4 : name_end].decode("utf-16le")
        except UnicodeDecodeError:
            continue
        if not name.startswith("autodesk.") or name_end + 4 > len(decoded):
            continue
        json_units = struct.unpack_from("<I", decoded, name_end)[0]
        json_end = name_end + 4 + json_units * 2
        if json_units > 10_000 or json_end > len(decoded):
            continue
        try:
            value = json.loads(decoded[name_end + 4 : json_end].decode("utf-16le"))
        except (UnicodeDecodeError, json.JSONDecodeError):
            continue
        objects[name] = value
    return objects


def constants(value: dict[str, object]) -> dict[str, object]:
    result: dict[str, object] = {}
    for item in value.get("constants", []):
        assert isinstance(item, dict)
        result[str(item["id"])] = item.get("typedValue", item.get("value"))
    return result


def typed_id(value: object) -> str:
    assert isinstance(value, dict) and isinstance(value.get("typeid"), str)
    return value["typeid"]


def generate_specs(registry_path: Path, output: Path) -> None:
    objects = registry_objects(registry_path)
    factors = {
        key: float(constants(value)["factor"])
        for key, value in objects.items()
        if key.startswith("autodesk.unit.factor")
    }
    memo: dict[str, tuple[int, float, float]] = {}

    def unit_transform(type_id: str) -> tuple[int, float, float]:
        """Return length exponent, unit-to-SI scale, and unit-to-SI offset."""
        if type_id in memo:
            return memo[type_id]
        value = objects[type_id]
        inherits = value.get("inherits", [])
        data = constants(value)
        if "autodesk.unit:unit.primitive.dimensional-1.0.0" in inherits:
            dimension = typed_id(data["dimension"])
            result = (1 if ":length-" in dimension else 0, 1.0, 0.0)
        elif "autodesk.unit:unit.primitive-1.0.0" in inherits:
            result = (0, 1.0, 0.0)
        elif "autodesk.unit:unit.absolute-1.0.0" in inherits:
            exponent, scale, parent_offset = unit_transform(typed_id(data["parentUnit"]))
            offset = float(data["offset"])
            result = (exponent, scale, parent_offset + offset * scale)
        elif "autodesk.unit:unit.derived-1.0.0" in inherits:
            exponent = 0
            scale = float(data.get("factor", 1.0))
            parent_units = data.get("parentUnits", {})
            assert isinstance(parent_units, dict)
            for parent, power_value in parent_units.items():
                power = int(power_value)
                parent_exponent, parent_scale, parent_offset = unit_transform(parent)
                if parent_offset != 0.0:
                    raise ValueError(f"absolute unit used in derived unit {type_id}")
                exponent += parent_exponent * power
                scale *= parent_scale**power
            parent_factors = data.get("parentFactors", {})
            assert isinstance(parent_factors, dict)
            for parent, power_value in parent_factors.items():
                scale *= factors[parent] ** int(power_value)
            result = (exponent, scale, 0.0)
        else:
            raise ValueError(f"unknown unit kind: {type_id}")
        memo[type_id] = result
        return result

    entries_by_key: dict[str, tuple[str, str, str, str, str, float, float]] = {}
    for type_id, value in objects.items():
        if not type_id.startswith("autodesk.spec."):
            continue
        data = constants(value)
        storage = data.get("storageUnit")
        if storage is None:
            continue
        storage_id = typed_id(storage)
        storage_name = str(constants(objects[storage_id])["name"])
        length_power, unit_scale, unit_offset = unit_transform(storage_id)
        internal_scale = FOOT_TO_METRE**length_power
        scale = internal_scale / unit_scale
        offset = -unit_offset / unit_scale
        if not math.isfinite(scale) or not math.isfinite(offset):
            raise ValueError(f"non-finite conversion for {type_id}")
        key = VERSION.sub("", type_id)
        candidate = (key, type_id, str(data["name"]), storage_id, storage_name, scale, offset)
        if key not in entries_by_key or type_id > entries_by_key[key][1]:
            entries_by_key[key] = candidate
    entries = sorted(entries_by_key.values())
    lines = [
        "// @generated by scripts/generate_revit_2023_catalog.py; do not edit.",
        "#![allow(clippy::excessive_precision, clippy::unreadable_literal)]",
        "use crate::Specification;",
        "",
        "pub(super) static VALUES: &[Specification] = &[",
    ]
    for key, type_id, name, storage, storage_name, scale, offset in entries:
        lines.append(
            "    Specification { "
            f"type_id: {rust_string(type_id)}, name: {rust_string(name)}, "
            f"storage_unit: {rust_string(storage)}, storage_unit_name: {rust_string(storage_name)}, "
            f"internal_to_storage_scale: {float(scale)!r}, "
            f"internal_to_storage_offset: {float(offset)!r}, key: {rust_string(key)} "
            "},"
        )
    lines.extend(["];"])
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"measurable specs: {len(entries)}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bip-2023", required=True, type=Path)
    parser.add_argument("--bic-2023", required=True, type=Path)
    parser.add_argument("--bip-values", required=True, action="append", type=Path)
    parser.add_argument("--bic-values", required=True, action="append", type=Path)
    parser.add_argument("--global-latest", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    generate_parameters(args.bip_2023, args.bip_values, args.output / "built_in_parameters_2023.rs")
    generate_categories(args.bic_2023, args.bic_values, args.output / "built_in_categories_2023.rs")
    generate_specs(args.global_latest, args.output / "specifications_2023.rs")


if __name__ == "__main__":
    main()
